general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'TÜV Rheinland Service GmbH #003_kymatest-fndq0vl6'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
